### ISSUE TITLE
Linking a program with gcc hangs

### ISSUE THREAD

**Issue by Sh4rK** [wishstudio/flinux#52]
Hi!

I tried compiling a program with gcc on the most recent version of flinux, and figured out that the compilation works fine, but at the very end of the linking step something causes a hang. The output executable is actually produced and working though.
In flog, I see 3 processes while hanging: the first is what I executed from bash, which is waiting for its child. The child executes another process, and waits for that. And the last one, the child of the child, has this log: http://pastebin.com/1e3qV52G 
What's interesting for me is the last 2 lines:

```
[13:27:49.392] (II) DBT block at [102f2000, 10305000) changed. Code cache flushed.
[13:27:49.392] (II) dbt code cache flushed.
```

It seems that after the code cache flushing, nothing happens, but I couldn't figure out more. Does anyone have any idea what's going on?

**Comment by wishstudio** [comment]
This one luckily triggers a nasty design flow in file mapping handling.

The issue is not due to the code cache flushing but the beforehand munmap() call. 

```
[08:50:48.446] (II) munmap(102fd000, 000136d4)
[08:50:48.446] (II) DBT block at [102fd000, 10310000) changed. Code cache flushed.
[08:50:48.447] (II) dbt code cache flushed.
```

The overall workflow is like this:
- The `munmap_internal()` function (used in `munmap()`) successfully freed the dbt block at [102fd000, 10310000) (which triggered the dbt code cache flushing). It then continues on to free the next map_entry which consists of one page 0x1031. It calls `free_map_entry_blocks()` to free the map entry.
- `free_map_entry_blocks()` find out that this entry is actually a file mapping so it calls `vfs_release()` on that file.
- In `vfs_release()` the reference counter of the file is decremented to zero, so it calls the actual destructor of the file object, which consists of some cleanups and a call to `kfree()` to free the memory.
- `kfree()` uses a pooled memory management. It frees the memory occupied by the file and it decrements the reference count on the allocation block (64KB) the file resides in. It then discovered the reference count becomes zero so the entire block can be freed. It happily calls `munmap()` to free it.
- BOOM! `munmap()` is re-entered and the multi-threaded r/w lock guard locks itself.

What a mess!

Something need to be done in heap or file handling to fix this problem. I'm still thinking how to fix this horrible design problem...

**Comment by Sh4rK** [comment]
Would it work with a recursive/reentrant RW lock, or would there be other problems as well? If it would, maybe we could implement one on top of the SRW lock.

**Comment by wishstudio** [comment]
If we go with recursive lock approach, we also have to make munmap() reentrant, which is nasty and error-prone that I want to avoid.

**Comment by Sh4rK** [comment]
Ok, another idea (just guessing though): isn't there a way to "break the cycle" and use native memory allocation/deallocation (or anything not based on mmap/munmap) in winfs, for example?
