### ISSUE TITLE
Proposal: Chocolatey

### ISSUE THREAD

**Issue by wjk** [wishstudio/flinux#78]
[Chocolatey](https://chocolatey.org) is a Windows package manager (sort of like `apt-get` on Linux). I have contributed to Chocolatey significantly, both by creating packages for it and by opening PRs on Chocolatey itself, and have created [a Chocolatey package](https://chocolatey.org/packages/flinux/0.21.1) for Foreign Linux. However, the Chocolatey maintainers have suggested that the package name `flinux` be reserved for the upstream version of Foreign Linux (i.e. your version, not my fork).

I am asking here if you are OK with giving my Chocolatey package your blessing as the “official” Chocolatey package for Foreign Linux. I can assume responsibility for handling issues raised against the Chocolatey package, if you are unwilling or unable to do so. If so, all I request is a bit of leeway as far as response times go, as I am a current college student, and my classes take up a lot of my time. Despite what I may prefer, I can’t spend _all_ my time on GitHub. :smile:

(If you would prefer that I submit the source files for the Chocolatey package to this repo instead, I can prepare a PR.)

**Comment by wishstudio** [comment]
I think a long term solution should be that we transfer this project to an organization once we've got enough attention and contributors. Currently the only real contributor is me so I don't rush to do this.

Transferring the "official" wording to you is not a long term plan since all links over the internet points to this repository instead of yours. Even if it is just wording thing, it will still cause confusions.

So for now please just prepare a working PR and I'll merge it. I won't release new versions frequently so don't worry if you need to update the package specs. Then when you've got enough commits into the repository beyond my threshold I'll give you commit access so you will be able to manage such things much more conveniently.

Anyway thanks for you attention for this and please understand my decisions :smile:
